In [107]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [108]:
df_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')
df_preprocessed.describe(include='all')

,Reason1,Reason2,Reason3,Reason4,Month,Day of the week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours
count,700,700,700,700,700.00000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000,700.000000
unique,2,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,False,False,False,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,525,694,637,418,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,6.36000,2.011429,222.347143,29.892857,36.417143,271.801774,26.737143,0.167143,1.021429,0.687143,6.761429
std,NaN,NaN,NaN,NaN,3.50501,1.480396,66.312960,14.804446,6.379083,40.021804,4.254701,0.373370,1.112215,1.166095,12.670082
min,NaN,NaN,NaN,NaN,1.00000,0.000000,118.000000,5.000000,27.000000,205.917000,19.000000,0.000000,0.000000,0.000000,0.000000
25%,NaN,NaN,NaN,NaN,3.00000,1.000000,179.000000,16.000000,31.000000,241.476000,24.000000,0.000000,0.000000,0.000000,2.000000
50%,NaN,NaN,NaN,NaN,6.00000,2.000000,225.000000,26.000000,37.000000,264.249000,25.000000,0.000000,1.000000,0.000000,3.000000
75%,NaN,NaN,NaN,NaN,10.00000,3.000000,260.000000,50.000000,40.000000,294.217000,31.000000,0.000000,2.000000,1.000000,8.000000
max,NaN,NaN,NaN,NaN,12.00000,6.000000,388.000000,52.000000,58.000000,378.884000,38.000000,1.000000,4.000000,8.000000,120.000000

In [109]:
df_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [110]:
targets = np.where(df_preprocessed['Absenteeism Time in Hours'] > df_preprocessed['Absenteeism Time in Hours'].median(), 
                   1, 0)
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0])

In [111]:
df_preprocessed['Targets'] = targets
df_preprocessed

,Reason1,Reason2,Reason3,Reason4,Month,Day of the week,Transportation Expense,Distance to Work,Age,Daily Work Load Average,Body Mass Index,Education,Children,Pets,Absenteeism Time in Hours,Targets
0,False,False,False,True,7,1,289,36,33,239.554,30,0,2,1,4,1
1,False,False,False,False,7,1,118,13,50,239.554,31,0,1,0,0,0
2,False,False,False,True,7,2,179,51,38,239.554,31,0,0,0,2,0
3,True,False,False,False,7,3,279,5,39,239.554,24,0,2,0,4,1
4,False,False,False,True,7,3,289,36,33,239.554,30,0,2,1,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,True,False,False,False,5,2,179,22,40,237.656,22,1,2,0,8,1
696,True,False,False,False,5,2,225,26,28,237.656,24,0,1,2,3,0
697,True,False,False,False,5,3,330,16,28,237.656,25,1,0,0,8,1
698,False,False,False,True,5,3,235,16,32,237.656,25,1,0,0,2,0
699,False,False,False,True,5,3,291,31,40,237.656,25,0,1,1,2,0

In [112]:
data_targets = df_preprocessed.drop(['Day of the week', 'Distance to Work', 'Daily Work Load Average', 'Absenteeism Time in Hours'], axis=1)

In [113]:
data_targets is df_preprocessed

False

In [114]:
data_targets

,Reason1,Reason2,Reason3,Reason4,Month,Transportation Expense,Age,Body Mass Index,Education,Children,Pets,Targets
0,False,False,False,True,7,289,33,30,0,2,1,1
1,False,False,False,False,7,118,50,31,0,1,0,0
2,False,False,False,True,7,179,38,31,0,0,0,0
3,True,False,False,False,7,279,39,24,0,2,0,1
4,False,False,False,True,7,289,33,30,0,2,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
695,True,False,False,False,5,179,40,22,1,2,0,1
696,True,False,False,False,5,225,28,24,0,1,2,0
697,True,False,False,False,5,330,28,25,1,0,0,1
698,False,False,False,True,5,235,32,25,1,0,0,0
699,False,False,False,True,5,291,40,25,0,1,1,0

In [115]:
# Median當作分界線比較穩定，因為他已經先把資料切成大概一半一半
# 45% ~ 55% is acceptable
data_targets['Targets'].sum() / data_targets.shape[0]

0.45571428571428574

### Select Features

In [116]:
# data_targets.loc[:, :'Pets']
data_without_targets = data_targets.iloc[:, :-1]

In [117]:
unscale_dummies = data_targets.loc[:, 'Reason1':'Reason4']
unscale_dummies.to_numpy

<bound method DataFrame.to_numpy of      Reason1  Reason2  Reason3  Reason4
0      False    False    False     True
1      False    False    False    False
2      False    False    False     True
3       True    False    False    False
4      False    False    False     True
..       ...      ...      ...      ...
695     True    False    False    False
696     True    False    False    False
697     True    False    False    False
698    False    False    False     True
699    False    False    False     True

[700 rows x 4 columns]>

In [118]:
unscale_dummies = pd.get_dummies(unscale_dummies, drop_first=True)
unscale_dummies

     Reason1  Reason2  Reason3  Reason4
0      False    False    False     True
1      False    False    False    False
2      False    False    False     True
3       True    False    False    False
4      False    False    False     True
..       ...      ...      ...      ...
695     True    False    False    False
696     True    False    False    False
697     True    False    False    False
698    False    False    False     True
699    False    False    False     True

[700 rows x 4 columns]

In [119]:
# Dummies no need to scale!
unscale_inputs = data_targets.iloc[:, 4:-1]
unscale_inputs

,Month,Transportation Expense,Age,Body Mass Index,Education,Children,Pets
0,7,289,33,30,0,2,1
1,7,118,50,31,0,1,0
2,7,179,38,31,0,0,0
3,7,279,39,24,0,2,0
4,7,289,33,30,0,2,1
...,...,...,...,...,...,...,...
695,5,179,40,22,1,2,0
696,5,225,28,24,0,1,2
697,5,330,28,25,1,0,0
698,5,235,32,25,1,0,0
699,5,291,40,25,0,1,1

In [120]:
scaler = StandardScaler()
scaled_inputs = scaler.fit_transform(unscale_inputs)

In [121]:
scaled_inputs

array([[ 0.18272635,  1.00584437, -0.53606239, ..., -0.44798003,
         0.88046927,  0.26848661],
       [ 0.18272635, -1.57468098,  2.13080317, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [ 0.18272635, -0.6541427 ,  0.24830984, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [-0.3882935 ,  1.62456682, -1.32043461, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.3882935 ,  0.19094163, -0.69293683, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.3882935 ,  1.03602595,  0.56205873, ..., -0.44798003,
        -0.01928035,  0.26848661]])

In [122]:
scaled_inputs.shape

(700, 7)

In [123]:
scaled_with_dummies = np.concatenate((unscale_dummies, scaled_inputs), axis=1)
scaled_with_dummies

array([[ 0.        ,  0.        ,  0.        , ..., -0.44798003,
         0.88046927,  0.26848661],
       [ 0.        ,  0.        ,  0.        , ..., -0.44798003,
        -0.01928035, -0.58968976],
       [ 0.        ,  0.        ,  0.        , ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.        ,  0.        ,  0.        , ...,  2.23224237,
        -0.91902997, -0.58968976],
       [ 0.        ,  0.        ,  0.        , ...,  2.23224237,
        -0.91902997, -0.58968976],
       [ 0.        ,  0.        ,  0.        , ..., -0.44798003,
        -0.01928035,  0.26848661]])

### Split dataset into train and test then shuffle

In [124]:
# random_state: Shuffle
x_train, x_test, y_train, y_test = train_test_split(scaled_with_dummies, targets, test_size=0.2, random_state=20)

In [125]:
print(x_train.shape, y_train.shape)

(560, 11) (560,)

In [126]:
print(x_test.shape, y_test.shape)

(140, 11) (140,)

### Logistic Regression Model

In [127]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [128]:
reg = LogisticRegression()
reg.fit(x_train, y_train)

LogisticRegression()

In [129]:
reg.score(x_train, y_train)

0.7732142857142857

In [130]:
# Manually Check Accuracy
reg_pred = reg.predict(x_train)

In [131]:
reg_pred == y_train

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True, False,
       False, False,  True,  True, False,  True, False,  True,  True,
        True, False,  True, False,  True, False,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True, False,
        True, False,  True, False,  True,  True,  True,  True, False,
        True, False, False,  True,  True,  True,  True,  True, False,
       False, False,  True, False,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True,  True,  True,  True,  True, False,  True,  True,
        True, False, False,  True,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True, False, False,
       False,  True,  True,  True,  True, False,  True, False,  True,
        True,  True,  True,  True,  True,  True, False,  True, False,
       False,  True,  True,  True,  True,  True, False,  True,  True,
        True,  True, False, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True, False,
       False,  True,  True,  True,  True,  True, False,  True, False,
        True,  True,  True, False, False,  True,  True,  True, False,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False,  True,  True,  True, False,  True,
        True, False,  True, False,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True, False,  True,  True, False,  True, False,
        True,  True,  True,  True,  True, False, False,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
       False,  True,  True,  True, False, False,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True, False, False,  True,  True,
       False,  True,  True,  True,  True,  True,  True, False, False,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True, False,  True,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True, False,  True,  True,
       False, False, False,  True,  True, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
       False,  True])

In [132]:
np.sum((reg_pred == y_train))

433

### Coefficient, Intercept

In [133]:
feature_names = data_without_targets.columns.values
feature_names

array(['Reason1', 'Reason2', 'Reason3', 'Reason4', 'Month',
       'Transportation Expense', 'Age', 'Body Mass Index', 'Education',
       'Children', 'Pets'], dtype=object)

In [134]:
summary_table = pd.DataFrame(columns=['Features'], data=feature_names)
summary_table['Coefficient'] = np.transpose(reg.coef_)
summary_table

                  Features  Coefficient
0                  Reason1     2.793758
1                  Reason2     0.953594
2                  Reason3     3.105463
3                  Reason4     0.830854
4                    Month     0.158528
5   Transportation Expense     0.604682
6                      Age    -0.170567
7          Body Mass Index     0.277805
8                Education    -0.084244
9                 Children     0.347340
10                    Pets    -0.277365

In [135]:
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

                  Features  Coefficient
0                Intercept    -1.674986
1                  Reason1     2.793758
2                  Reason2     0.953594
3                  Reason3     3.105463
4                  Reason4     0.830854
5                    Month     0.158528
6   Transportation Expense     0.604682
7                      Age    -0.170567
8          Body Mass Index     0.277805
9                Education    -0.084244
10                Children     0.347340
11                    Pets    -0.277365

In [136]:
# A feature is not particularly important:
# if Coefficient is around 0
# if odds ratio is around 1
# -> Daily Work Load Average, Distance to Work, Day of the week, Education
summary_table['Odds_Ratio'] = np.exp(summary_table.Coefficient)
summary_table.sort_values('Odds_Ratio', ascending=False)

                  Features  Coefficient  Odds_Ratio
3                  Reason3     3.105463   22.319550
1                  Reason1     2.793758   16.342326
2                  Reason2     0.953594    2.595018
4                  Reason4     0.830854    2.295277
6   Transportation Expense     0.604682    1.830669
10                Children     0.347340    1.415298
8          Body Mass Index     0.277805    1.320228
5                    Month     0.158528    1.171785
9                Education    -0.084244    0.919207
7                      Age    -0.170567    0.843186
11                    Pets    -0.277365    0.757778
0                Intercept    -1.674986    0.187311

- Reason1 (Various Diseases): 生病通常也不會去上班，所以Coefficient, Odds_Ratio也是偏高。

- Reason2 (Pregnency, Giving birth): 有些懷孕還是會上班，所以Coefficient, Odds_Ratio會有所下降。

- Reason3 (Poisoning): Coefficient, Odds_Ratio都是最高的（因為中毒一定不會去上班)。

- Reason4 (Light Diseases): 很多人輕微感冒還是會去上班，不太會請假，所以Coefficient, Odds_Ratio會有所下降。

- Daily Work Load Average, Distance to Work有些出乎意料，對於空班率來說影響較小。 -> Drop

### Testing Model

In [137]:
reg.score(x_test, y_test)

0.75

In [138]:
predict_proba = reg.predict_proba(x_test)
predict_proba

array([[0.71328706, 0.28671294],
       [0.5868545 , 0.4131455 ],
       [0.44134189, 0.55865811],
       [0.78134024, 0.21865976],
       [0.08390289, 0.91609711],
       [0.33416409, 0.66583591],
       [0.29892189, 0.70107811],
       [0.13152486, 0.86847514],
       [0.78543137, 0.21456863],
       [0.74884244, 0.25115756],
       [0.493633  , 0.506367  ],
       [0.22472141, 0.77527859],
       [0.07133356, 0.92866644],
       [0.73452626, 0.26547374],
       [0.30947706, 0.69052294],
       [0.54998141, 0.45001859],
       [0.55004133, 0.44995867],
       [0.53881581, 0.46118419],
       [0.40123117, 0.59876883],
       [0.05377404, 0.94622596],
       [0.69951499, 0.30048501],
       [0.78134024, 0.21865976],
       [0.41930999, 0.58069001],
       [0.41930999, 0.58069001],
       [0.24735108, 0.75264892],
       [0.74484338, 0.25515662],
       [0.5097579 , 0.4902421 ],
       [0.85787351, 0.14212649],
       [0.20371958, 0.79628042],
       [0.78134024, 0.21865976],
       [0.62995476, 0.37004524],
       [0.31955356, 0.68044644],
       [0.31433413, 0.68566587],
       [0.47103442, 0.52896558],
       [0.78134024, 0.21865976],
       [0.46494088, 0.53505912],
       [0.77770502, 0.22229498],
       [0.26277065, 0.73722935],
       [0.59557628, 0.40442372],
       [0.39470973, 0.60529027],
       [0.78897452, 0.21102548],
       [0.54907292, 0.45092708],
       [0.76166312, 0.23833688],
       [0.59947932, 0.40052068],
       [0.1727422 , 0.8272578 ],
       [0.43162608, 0.56837392],
       [0.30779766, 0.69220234],
       [0.71328706, 0.28671294],
       [0.77990377, 0.22009623],
       [0.79641172, 0.20358828],
       [0.42532529, 0.57467471],
       [0.67142105, 0.32857895],
       [0.33416409, 0.66583591],
       [0.72978602, 0.27021398],
       [0.16632114, 0.83367886],
       [0.56474796, 0.43525204],
       [0.11624187, 0.88375813],
       [0.76812082, 0.23187918],
       [0.66500046, 0.33499954],
       [0.65484324, 0.34515676],
       [0.30287312, 0.69712688],
       [0.3443091 , 0.6556909 ],
       [0.70700883, 0.29299117],
       [0.20765856, 0.79234144],
       [0.79195908, 0.20804092],
       [0.73143694, 0.26856306],
       [0.91177591, 0.08822409],
       [0.77770502, 0.22229498],
       [0.26707698, 0.73292302],
       [0.69776219, 0.30223781],
       [0.77770502, 0.22229498],
       [0.7078877 , 0.2921123 ],
       [0.09587832, 0.90412168],
       [0.54010349, 0.45989651],
       [0.39842415, 0.60157585],
       [0.78134024, 0.21865976],
       [0.22663283, 0.77336717],
       [0.27082193, 0.72917807],
       [0.25733038, 0.74266962],
       [0.32801697, 0.67198303],
       [0.75334967, 0.24665033],
       [0.92333213, 0.07666787],
       [0.76812082, 0.23187918],
       [0.24639814, 0.75360186],
       [0.56535186, 0.43464814],
       [0.87855157, 0.12144843],
       [0.29515927, 0.70484073],
       [0.41930999, 0.58069001],
       [0.75704919, 0.24295081],
       [0.31955356, 0.68044644],
       [0.82650907, 0.17349093],
       [0.8491335 , 0.1508665 ],
       [0.77350904, 0.22649096],
       [0.73143694, 0.26856306],
       [0.74884244, 0.25115756],
       [0.14895476, 0.85104524],
       [0.7039421 , 0.2960579 ],
       [0.23639852, 0.76360148],
       [0.75571365, 0.24428635],
       [0.78406544, 0.21593456],
       [0.37693965, 0.62306035],
       [0.31955356, 0.68044644],
       [0.30288791, 0.69711209],
       [0.257317  , 0.742683  ],
       [0.55132377, 0.44867623],
       [0.5175519 , 0.4824481 ],
       [0.72245336, 0.27754664],
       [0.14895476, 0.85104524],
       [0.22377364, 0.77622636],
       [0.85484059, 0.14515941],
       [0.92949967, 0.07050033],
       [0.09628895, 0.90371105],
       [0.33638944, 0.66361056],
       [0.66101193, 0.33898807],
       [0.47621656, 0.52378344],
       [0.43868224, 0.56131776],
       [0.21362932, 0.78637068],
       [0.17790927, 0.82209073],
       [0.45773412, 0.54226588],
       [0.68991628, 0.31008372],
       [0.7402343 , 0.2597657 ],
       [0.84050026, 0.15949974],
       [0.18775439, 0.81224561],
       [0.54907292, 0.45092708],
       [0.78134024, 0.21865976],
       [0.64802226, 0.35197774],
       [0.78897452, 0.21102548],
       [0.88991884, 0.11008116],
       [0.2589367 , 0.7410633 ],
       [0.69951499, 0.30048501],
       [0.38394927, 0.61605073],
       [0.78897452, 0.21102548],
       [0.7039421 , 0.2960579 ],
       [0.64802226, 0.35197774],
       [0.73432636, 0.26567364],
       [0.47621656, 0.52378344],
       [0.53881581, 0.46118419],
       [0.68813245, 0.31186755],
       [0.75571365, 0.24428635],
       [0.54010349, 0.45989651]])

In [139]:
predict_proba.shape

(140, 2)

In [140]:
# 找出預測為1的所有機率
predict_proba[:, 1]

array([0.28671294, 0.4131455 , 0.55865811, 0.21865976, 0.91609711,
       0.66583591, 0.70107811, 0.86847514, 0.21456863, 0.25115756,
       0.506367  , 0.77527859, 0.92866644, 0.26547374, 0.69052294,
       0.45001859, 0.44995867, 0.46118419, 0.59876883, 0.94622596,
       0.30048501, 0.21865976, 0.58069001, 0.58069001, 0.75264892,
       0.25515662, 0.4902421 , 0.14212649, 0.79628042, 0.21865976,
       0.37004524, 0.68044644, 0.68566587, 0.52896558, 0.21865976,
       0.53505912, 0.22229498, 0.73722935, 0.40442372, 0.60529027,
       0.21102548, 0.45092708, 0.23833688, 0.40052068, 0.8272578 ,
       0.56837392, 0.69220234, 0.28671294, 0.22009623, 0.20358828,
       0.57467471, 0.32857895, 0.66583591, 0.27021398, 0.83367886,
       0.43525204, 0.88375813, 0.23187918, 0.33499954, 0.34515676,
       0.69712688, 0.6556909 , 0.29299117, 0.79234144, 0.20804092,
       0.26856306, 0.08822409, 0.22229498, 0.73292302, 0.30223781,
       0.22229498, 0.2921123 , 0.90412168, 0.45989651, 0.60157585,
       0.21865976, 0.77336717, 0.72917807, 0.74266962, 0.67198303,
       0.24665033, 0.07666787, 0.23187918, 0.75360186, 0.43464814,
       0.12144843, 0.70484073, 0.58069001, 0.24295081, 0.68044644,
       0.17349093, 0.1508665 , 0.22649096, 0.26856306, 0.25115756,
       0.85104524, 0.2960579 , 0.76360148, 0.24428635, 0.21593456,
       0.62306035, 0.68044644, 0.69711209, 0.742683  , 0.44867623,
       0.4824481 , 0.27754664, 0.85104524, 0.77622636, 0.14515941,
       0.07050033, 0.90371105, 0.66361056, 0.33898807, 0.52378344,
       0.56131776, 0.78637068, 0.82209073, 0.54226588, 0.31008372,
       0.2597657 , 0.15949974, 0.81224561, 0.45092708, 0.21865976,
       0.35197774, 0.21102548, 0.11008116, 0.7410633 , 0.30048501,
       0.61605073, 0.21102548, 0.2960579 , 0.35197774, 0.26567364,
       0.52378344, 0.46118419, 0.31186755, 0.24428635, 0.45989651])